version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_csv
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: csvjobs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_csv
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"      # Porta AMQP (fila)
      - "15672:15672"    # Dashboard web
    restart: unless-stopped

volumes:
  pgdata: